server.port: 7002
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: price-db

logging:
  level:
    root: INFO
    ec.carper: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.config.activate.on-profile: docker
spring.data.mongodb.host: mongodb
server.port: 8080
