server.port: 7000
server.error.include-message: always

app:
  product-service:
    host: localhost
    port: 7001
  price-service:
    host: localhost
    port: 7002

logging:
  level:
    root: INFO
    ec.carper: DEBUG

---
spring.profiles: docker

server.port: 8080

app:
  product-service:
    host: localhost
    port: 8080
  price-service:
    host: localhost
    port: 8080
